### ISSUE TITLE
Error converting from MiXCR 3.0.1

### ISSUE THREAD

**Issue by JohnMCMa** [mikessh/vdjtools#109]
I am using VDJTools 1.2.1 to convert some MiXCR 3.0.1 exportClones output (with `-o -p -c TRA -p full`) but got an error as follows:

````
[Tue Nov 13 11:18:22 CST 2018 BEGIN]
[Script]
Convert
[CommandLine]
executing vdjtools-1.2.1.jar Convert -S mixcr -m /scratch/lym_myl_rsch/mma/Green/TCR/output/MiXCR-TRA-convert.metadata.txt /scratch/lym_myl_rsch/mma/Green/TCR/output/VDJTools/CAR-T-TRA
[Message]
java.lang.RuntimeException: Unable to parse clonotype string 18	656.0	0.010748283715367096	CCCAGTCGGTGACCCAGCTTGGCAGCCACGTCTCTGTCTCTGGTGGGAAC,GCAATACCCCAACCAAGGACTCCAGCTTCTCCTGAAGTACACAACAGGGGCCACCCTGGTTAAAGGCATCAACGGTTTTGAGGCTGAATTTAAGAAGAGTGAAACCTCCTTCCACCTGACGAAACCCTCAGCCCATATGAGCGACGCGGCTGAGTACTTCTGTGCTGTGAGTGACCAGGCAGGAACTGCTCTGATCTTTGGGAAGGGAACCACCTTATCAGTGAGTTCCAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGA,TCCAGTCTGACACCCACCAGCCCCAGGACTTGAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGA	9[8/0.65/05/77</3731318//16(2.*3*0.[%[$%-[$$$$$+$[,7737704;774:675779665:8>5:498347:8=:;:?56666>5:7488;@68>[6=<??;:?<BB<>:;98=89B?B<<?B[;[?<::=[==[=:=<;B=6:?:[B:9:=BB[<B9[[:B:<<:?<8:=7[;[[[<7B9;<7BB9B?[;<[[B[B=9///////////////////////////////////////[[[[[[==[=?8;[;B?[-=[[[<B[7-[<[78<79888[7[;8788:=8699459/6:667855:67667,[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[	TRAV8-4*01(997),TRAV8-4*04(992.9),TRAV8-4*05(980.3),TRAV8-4*02(980.1),TRAV8-4*03(980.1)		TRAJ15*01(277.2)		1|50|304|0|50|I42GSA43TSA44GSG48A|191.0,110|287|304|0|177|ST153ASC157GST284C|843.0,;,270|287|304|160|177|ST284C|71.0,;,270|287|304|160|177|ST284C|71.0,;,270|287|304|160|177|ST284C|71.0,;,270|276|296|160|166||30.0,		,23|80|80|173|230||285.0,								TACACAACAGGGGCCACCCTGGTT	19	AAAGGCATCAACGGTTTTGAGGCTGAATTTAAGAAGAGTGAAACCTCCTTCCACCTGACGAAACCCTCAGCCCATATGAGCGACGCGGCTGAGTACTTC	21	TGTGCTGTGAGTGACCAGGCAGGAACTGCTCTGATCTTT	14	GGGAAGGGAACCACCTTATCAGTGAGTTCCA	12				YTTGATLV	KGINGFEAEFKKSETSFHLTKPSAHMSDAAEYF	CAVSDQAGTALIF	GKGTTLSVSS_	:::::::::::::::::::::,:::::::37:61:160:3:177:::::173:-3:199:230::,::::::::::::::::::::: for MiXcr input type: For input string: ",270"
[StackTrace-Short]
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:189)
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy:249)
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy)
com.antigenomics.vdjtools.sample.Sample.fromInputStream(Sample.java:174)
com.antigenomics.vdjtools.sample.Sample$fromInputStream.call(Unknown Source)
com.antigenomics.vdjtools.io.SampleStreamConnection._load(SampleStreamConnection.groovy:128)
com.antigenomics.vdjtools.io.SampleStreamConnection.getSample(SampleStreamConnection.groovy:139)
com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy:320)
com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy)
com.antigenomics.vdjtools.misc.Convert.run(Convert.groovy:94)
com.antigenomics.vdjtools.misc.Convert$run.call(Unknown Source)
com.antigenomics.vdjtools.misc.ExecUtil.run(ExecUtil.groovy:94)
com.antigenomics.vdjtools.misc.ExecUtil$run.call(Unknown Source)
com.antigenomics.vdjtools.VdjTools.run(VdjTools.groovy:226)
com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)
[StackTrace-Full]
java.lang.RuntimeException: Unable to parse clonotype string 18	656.0	0.010748283715367096	CCCAGTCGGTGACCCAGCTTGGCAGCCACGTCTCTGTCTCTGGTGGGAAC,GCAATACCCCAACCAAGGACTCCAGCTTCTCCTGAAGTACACAACAGGGGCCACCCTGGTTAAAGGCATCAACGGTTTTGAGGCTGAATTTAAGAAGAGTGAAACCTCCTTCCACCTGACGAAACCCTCAGCCCATATGAGCGACGCGGCTGAGTACTTCTGTGCTGTGAGTGACCAGGCAGGAACTGCTCTGATCTTTGGGAAGGGAACCACCTTATCAGTGAGTTCCAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGA,TCCAGTCTGACACCCACCAGCCCCAGGACTTGAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGA	9[8/0.65/05/77</3731318//16(2.*3*0.[%[$%-[$$$$$+$[,7737704;774:675779665:8>5:498347:8=:;:?56666>5:7488;@68>[6=<??;:?<BB<>:;98=89B?B<<?B[;[?<::=[==[=:=<;B=6:?:[B:9:=BB[<B9[[:B:<<:?<8:=7[;[[[<7B9;<7BB9B?[;<[[B[B=9///////////////////////////////////////[[[[[[==[=?8;[;B?[-=[[[<B[7-[<[78<79888[7[;8788:=8699459/6:667855:67667,[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[	TRAV8-4*01(997),TRAV8-4*04(992.9),TRAV8-4*05(980.3),TRAV8-4*02(980.1),TRAV8-4*03(980.1)		TRAJ15*01(277.2)		1|50|304|0|50|I42GSA43TSA44GSG48A|191.0,110|287|304|0|177|ST153ASC157GST284C|843.0,;,270|287|304|160|177|ST284C|71.0,;,270|287|304|160|177|ST284C|71.0,;,270|287|304|160|177|ST284C|71.0,;,270|276|296|160|166||30.0,		,23|80|80|173|230||285.0,								TACACAACAGGGGCCACCCTGGTT	19	AAAGGCATCAACGGTTTTGAGGCTGAATTTAAGAAGAGTGAAACCTCCTTCCACCTGACGAAACCCTCAGCCCATATGAGCGACGCGGCTGAGTACTTC	21	TGTGCTGTGAGTGACCAGGCAGGAACTGCTCTGATCTTT	14	GGGAAGGGAACCACCTTATCAGTGAGTTCCA	12				YTTGATLV	KGINGFEAEFKKSETSFHLTKPSAHMSDAAEYF	CAVSDQAGTALIF	GKGTTLSVSS_	:::::::::::::::::::::,:::::::37:61:160:3:177:::::173:-3:199:230::,::::::::::::::::::::: for MiXcr input type: For input string: ",270"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy:249)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy4.next(Unknown Source)
	at com.antigenomics.vdjtools.sample.Sample.fromInputStream(Sample.java:174)
	at com.antigenomics.vdjtools.sample.Sample$fromInputStream.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.antigenomics.vdjtools.io.SampleStreamConnection._load(SampleStreamConnection.groovy:128)
	at com.antigenomics.vdjtools.io.SampleStreamConnection.getSample(SampleStreamConnection.groovy:139)
	at com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy:320)
	at com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy4.next(Unknown Source)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2209)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2191)
	at org.codehaus.groovy.runtime.dgm$194.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:223)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.antigenomics.vdjtools.misc.Convert.run(Convert.groovy:94)
	at com.antigenomics.vdjtools.misc.Convert$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.antigenomics.vdjtools.misc.ExecUtil.run(ExecUtil.groovy:94)
	at com.antigenomics.vdjtools.misc.ExecUtil$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.antigenomics.vdjtools.VdjTools.run(VdjTools.groovy:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1018)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1001)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)
Caused by: java.lang.NumberFormatException: For input string: ",270"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.codehaus.groovy.runtime.StringGroovyMethods.toInteger(StringGroovyMethods.java:3495)
	at org.codehaus.groovy.runtime.dgm$1214.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.antigenomics.vdjtools.io.parser.MiXcrParser.parseAlignments(MiXcrParser.groovy:164)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:209)
	at com.antigenomics.vdjtools.io.parser.MiXcrParser.innerParse(MiXcrParser.groovy:131)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:159)
	... 78 more
[END]
````

Any ideas what it could be?

**Comment by SeanGriffith** [comment]
I stumbled upon the same problem and found that it is tripped up by commas that seem to be written by the mixcr exportClones routine.

Using the command below I was able to convert my file so that it can be imported into VDJtools:
`sed -e 's/\s,\+/\t/g' -e 's/,\+\s/\t/g' mixcr3_exportClones_output.txt | sed -e 's/;,\+/;/g'`

Hope it can help someone
