### ISSUE TITLE
java.lang.RuntimeException: Unable to parse clonotype string [...] for VDJtools input type: toIndex = 7

### ISSUE THREAD

**Issue by jmelero611** [mikessh/vdjtools#150]
Hi there! 

I have been dealing with this error, but I have no idea what is it and how to solve it. First I thought it was because the sequence was too short (less than 7), but it actually happens in also larger sequences.

Any idea about what is causing the error and how to solve it?

Thank you very much for your help!

Here I leave the log:

[Mon May 31 11:28:06 CEST 2021 BEGIN]
[Script]
CalcBasicStats
[CommandLine]
executing vdjtools-1.2.1.jar CalcBasicStats -m metadata.txt output
[Message]
java.lang.RuntimeException: Unable to parse clonotype string 88	0.0003630183324257875	TGTGCCAGCGAGGATCTGAGAAAT	CASEDLRN	TRBV12-2+TRBV13-2		 for VDJtools input type: toIndex = 7
[StackTrace-Short]
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:189)
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy:249)
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy)
com.antigenomics.vdjtools.sample.Sample.fromInputStream(Sample.java:174)
com.antigenomics.vdjtools.sample.Sample$fromInputStream.call(Unknown Source)
com.antigenomics.vdjtools.io.SampleStreamConnection._load(SampleStreamConnection.groovy:128)
com.antigenomics.vdjtools.io.SampleStreamConnection.getSample(SampleStreamConnection.groovy:139)
com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy:320)
com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy)
com.antigenomics.vdjtools.basic.CalcBasicStats$_run_closure1.doCall(CalcBasicStats.groovy:102)
com.antigenomics.vdjtools.basic.CalcBasicStats.run(CalcBasicStats.groovy:93)
com.antigenomics.vdjtools.basic.CalcBasicStats$run.call(Unknown Source)
com.antigenomics.vdjtools.misc.ExecUtil.run(ExecUtil.groovy:94)
com.antigenomics.vdjtools.misc.ExecUtil$run.call(Unknown Source)
com.antigenomics.vdjtools.VdjTools.run(VdjTools.groovy:226)
com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)
[StackTrace-Full]
java.lang.RuntimeException: Unable to parse clonotype string 88	0.0003630183324257875	TGTGCCAGCGAGGATCTGAGAAAT	CASEDLRN	TRBV12-2+TRBV13-2		 for VDJtools input type: toIndex = 7
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:189)
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy:249)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy6.next(Unknown Source)
	at com.antigenomics.vdjtools.sample.Sample.fromInputStream(Sample.java:174)
	at com.antigenomics.vdjtools.sample.Sample$fromInputStream.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.antigenomics.vdjtools.io.SampleStreamConnection._load(SampleStreamConnection.groovy:128)
	at com.antigenomics.vdjtools.io.SampleStreamConnection.getSample(SampleStreamConnection.groovy:139)
	at com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy:320)
	at com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:54)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	at com.sun.proxy.$Proxy6.next(Unknown Source)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2294)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2280)
	at org.codehaus.groovy.runtime.dgm$181.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:223)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.antigenomics.vdjtools.basic.CalcBasicStats$_run_closure1.doCall(CalcBasicStats.groovy:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at groovy.lang.Closure.call(Closure.java:437)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withWriter(IOGroovyMethods.java:1139)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withPrintWriter(ResourceGroovyMethods.java:2115)
	at org.codehaus.groovy.runtime.dgm$1073.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.antigenomics.vdjtools.basic.CalcBasicStats.run(CalcBasicStats.groovy:93)
	at com.antigenomics.vdjtools.basic.CalcBasicStats$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.antigenomics.vdjtools.misc.ExecUtil.run(ExecUtil.groovy:94)
	at com.antigenomics.vdjtools.misc.ExecUtil$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.antigenomics.vdjtools.VdjTools.run(VdjTools.groovy:226)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1018)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1001)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 7
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.AbstractList.subList(AbstractList.java:497)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:7540)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:7778)
	at org.codehaus.groovy.runtime.dgm$320.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.antigenomics.vdjtools.io.parser.BaseParser.innerParse(BaseParser.groovy:73)
	at com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:159)
	... 95 more
[END]

**Comment by f6v** [comment]
@jmelero611  have you ever figured it out?
